### ISSUE TITLE
Design overhaul

### ISSUE THREAD

**Issue by denizongar** [sburba/ToTheComments#2]
I was thinking something along the lines of 
![new design](https://cloud.githubusercontent.com/assets/8755305/24636761/1e0ad1a8-18a2-11e7-855f-96dea873ecf5.jpg)

Removed the list styling, added dividers and gave the links the same color you used on the logo.
I can't quite put my fingers on it, but something is off. Let me know what you think.

**Comment by sburba** [comment]
This looks really good! I think maybe we should make the font size smaller too.

**Comment by sburba** [comment]
This is in the store now. Always looking for improvements though.
